### ISSUE TITLE
PAIN [vid 23-24]

### ISSUE THREAD

**Issue by prathimacode-hub** [SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare#26] opened 2021-07-13 09:49 UTC
Work on extracting 50 RGB images of the baby's facial expressions from each video. Later, convert the 50 RGB images to gray scale images. So, you will be extracting totally 100 images from each video. You have been assigned with 2 videos i.e., video [23-24] in the dataset present under 'Pain' folder which contains 49 videos.

Dataset Link: https://livemissouristate-my.sharepoint.com/:f:/g/personal/nyc10040_missouristate_edu/Ev2GCLuXRK1DsgbeiRGRywkBBzLLqRH-OKaMi3rFHuM3iA?e=Zm3XcU
Password: 3maF'N+53xKj{

Click on iCOPEvid folder inside the link and download only the video datasets to your desktops that are assigned to you here and start working.

**Comment by MrNobody09** [comment] 2021-07-13 10:48
can i take this issue?

**Comment by prathimacode-hub** [comment] 2021-07-13 10:49
Follow the issue template to get this isssue assigned. @MrNobody09

**Comment by MrNobody09** [comment] 2021-07-13 10:59
sorry to disturb you again, but i am using github for the first time.
can you tell me how to follow the issue template  so that i get assigned to it and start my contribution

**Comment by prathimacode-hub** [comment] 2021-07-13 11:07
Ok, there is a Issue template link provided in README file of the project. To be clear, here is the link. You should always go through the README and PROJECT DESCRIPTION. that would resolve half of your doubts. No worries. 

This is the link : https://github.com/SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

Copy and paste the template, fill the details acoordingly to your issue, add your things up, ur ideas, your approach you will follow. For this. You just have up to put here in new comment or can edit your existing comment. @MrNobody09

**Comment by MrNobody09** [comment] 2021-07-13 11:21
title: AI-ML-for-Newborn-Babies-in-Healthcare
about: Extract Images from mentioned Videos and divide them into the Image_Dataset folder.
name: Nalin
label: Issue#26
Assignee: ''

Define You:

- [✔ ]   DevIncept Participant

 

- [ ] Contributor

I wish to contribute even after 30 days.
Have you talked to any of the Moderators or Project Admin (Prathima Kadari) before creating this issue?
Yes

Is your feature request related to a problem? Please describe.
It is related to the above-mentioned issue.

A clear and concise description of what the problem is.
One is supposed to extract 50 images frames of color also to convert these into grayscale images and divide them based on facial expressions into Image_Dataset folders(no pain, mild, moderate, severe).

Describe the solution you'd like...
I will be extracting  50 RGB images of the videos also converting these 50 into grayscale images using OpenCV in Python and then I will divide them into 4 folders(no pain, mild, moderate, severe).

A clear and concise description of what you want to happen.
Classify the image frames based on facial expressions.

**Comment by prathimacode-hub** [comment] 2021-07-13 11:25
Great, assigned. Add up your full name to this comment. You can do it by selecting ... dots and you get an edit option.  @MrNobody09

**Comment by prathimacode-hub** [comment] 2021-08-02 14:17
Its been 20 days, and no update form you yet neither any PR. @MrNobody09

**Comment by prathimacode-hub** [comment] 2021-08-09 07:46
It has been 27 days, you never cared to turn up with progress neither with PR. So unfortunately your issue is unassigned. @MrNobody09

**Comment by MrNobody09** [comment] 2021-08-09 08:29
> It has been 27 days, you never cared to turn up with progress neither with PR. So unfortunately your issue is unassigned. @MrNobody09

I am sorry sir for the delay but I have been diagnosed as COVID-positive and because of the sickness i was not able to start my work.

**Comment by MrNobody09** [comment] 2021-08-09 08:31
but now i am in a better condition and I have completed the code so please assign me this issuesand I will make the pull request today itself.

**Comment by MrNobody09** [comment] 2021-08-09 08:39
I am sorry sir but i have been diagnosed as Covid-positive and because of
the sickness I was not able to start my contribution. But now I  am in a
better condition and I have completed my code so please assign me the issue
again and I will make the pull request today itself.

**Comment by prathimacode-hub** [comment] 2021-08-09 09:22
Ok, issue assigned. @MrNobody09

**Closed** 2021-08-09 10:37 UTC
Labels: Assigned, DCP21
